### ISSUE TITLE
Auto Nest Subdirectories works only on top level subdirectories

### ISSUE THREAD

**Issue by okolenmi** [rgthree/rgthree-comfy#369]
Only top subdirectories are nested in folders. Content of every top folder is just a long list without a possibility to filter something by name, even when number of items to nest was set to 1. I'm not sure is it a problem of a new version of ComfyUI or another OS. (I'm using Ubuntu, everything was OK on windows with older ComfyUI version)

**Comment by LukeG89** [comment]
It seems to work fine in latest ComfyUI (portable). I'm on Windows.

Number of item is set to 4.

![nesting](https://github.com/user-attachments/assets/32af81fd-ea62-474a-98e4-74366b292651)

**Comment by JoeNavark** [comment]
try disabling the easy-use module

**Comment by MediaSnatch** [comment]
> Only top subdirectories are nested in folders. Content of every top folder is just a long list without a possibility to filter something by name, even when number of items to nest was set to 1. I'm not sure is it a problem of a new version of ComfyUI or another OS. (I'm using Ubuntu, everything was OK on windows with older ComfyUI version)

Did you ever figure this out. Same issue. All I have installed is newest portable, rgthree and the manager.

**Comment by lycos2019** [comment]
same issue here. search doesn't detect files in sub folders

**Comment by GreenGhost21** [comment]
Having the issue as well. Guessing something happened with ComfyUI that broke this feature?

**Comment by ragscoon** [comment]
Same issue here, The LoRA loader will only work for the first level of directories but won't nest any further. I am on windows and my ComfyUI version is v0.3.14

![Image](https://github.com/user-attachments/assets/91816420-71a2-416d-bced-a6eef8977213)

**Comment by rgthree** [comment]
I can see the same thing. I wonder how comfy broke this. It looks like submenu items are no longer invoking their own ContextMenu.

I may have to find a different fix for this..

**Comment by rgthree** [comment]
Okay, I think this is fixed with the latest. I can see why it's not working within the ComfyUI LiteGraph code, but I also don't see any recent change.. so not sure what happened and hopefully the fix works well.

**Comment by LukeG89** [comment]
> Okay, I think this is fixed with the latest. I can see why it's not working within the ComfyUI LiteGraph code, but I also don't see any recent change.. so not sure what happened and hopefully the fix works well.

@rgthree FYI, the change that broke it was introduced in 1.9.3 frontend, 1.9.2 was working correctly

**Comment by PsypmP** [comment]
It never worked and still doesn't. I didn't even know you could have more than one level of nesting in this menu. Does anyone know how to fix it? I assume something else is interfering. Since I've never seen this feature working, I've been using Comfi for over three years.

**Comment by Zopiac** [comment]
All I know is that on my (very old) version of ComfyUI it works fine. Updating probably broke it (and probably other things) with the new menu system and everything, so I'm "stuck" on v1.8.13 so a to not have a broken personal workflow.
