### ISSUE TITLE
Auto Nest Subdirectories searching only searches within the open folder.

### ISSUE THREAD

**Issue by brknsoul** [rgthree/rgthree-comfy#417]
When enabling Auto Nest Subdirectories, attempting to search only searches within the open 'nest', rather than everything.

![Image](https://github.com/user-attachments/assets/e8876a0a-f345-498a-86ed-c66f4dad96d7)

**Comment by rgthree** [comment]
Okay, I think this is fixed with the latest.

**Comment by brknsoul** [comment]
Nope. Still not fixed. Still can't search models without opening its folder.

**Comment by brknsoul** [comment]
Request re-open.

**Comment by rgthree** [comment]
> Slightly off-topic, but you managed to fix this one

@kaalibro Nice. Are those from files issues (so I can close?).

> Nope. Still not fixed. Still can't search models without opening its folder.

@brknsoul Ah, yes. There was an issue where sub-folders didn’t have the search bar at all; that’s what the fix was (to bring it back).

As for the initial reported issue, unfortunately, that’s not something that I can fix, because it’s all just using ComfyUI’s regular ContextMenu’s which behave that way (with the search bar searching the current list).

**Comment by brknsoul** [comment]
Okay, Mebe I'll bring it up with ComfyUI and see what they can do.
